language: python
puthon: 3.8
script: 
  - pytest
#Сборка
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    repo: XSkeolan/TravisIntegration
    branch: master
    tags: false
