import:
- source: .travis/test.yml
  if: branch = dev || branch = master || branch = issue-4

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $d06313c62aabff231cba17d04c3fe548cf300666
  on:
    tags: false
    pre-release: true
    tag_name: "pre1"
    repo: XSkeolan/TravisIntegration
