language: python
python: 3.8
script:
  - pytest
  #- python3 aboutTests.py
  #- echo "Tagging the release"
  #- git tag "v.0.1.1"
  #- git push https://${GH_TOKEN}@github.com/XSkeolan/TravisIntegration v.0.1.1
deploy:
  provider: releases
  prerelease: true
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    repo: XSkeolan/TravisIntegration
    branch: dev
    tags: false
