language: bash

script:
  - DEPLOY_TIME := $(shell date -u +"%Y-%m-%dT%H-%M-%SZ_%s")
  - echo "Tagging the release"
  - git tag "$(DEPLOY_TIME)"
  - git push https://${GH_TOKEN}@github.com/XSkeolan/TravisIntegration $(DEPLOY_TIME)
